(import (except (scheme base)
                vector-length
                make-vector
                vector-ref
                vector-set!
                length
                vector->list
                list->vector
                cons
                car
                cdr
                pair?
                negative?
                positive?
                zero?
                not) (only (scheme r5rs) exact->inexact) (scheme write) (prefix (hawk sys) sys:))

(define (negative? a) (< a 0))
(define (positive? a) (> a 0))
(define (zero? a) (= a 0))
(define (cons a b)
  (let ((cell (sys:ALLOC 24 3))) (sys:STORE cell a 0) (sys:STORE cell b 1) cell))

(define (cdr a) (sys:LOAD a 1))
(define (car a) (sys:LOAD a 0))

(define (not a) (if a #f #t))
(define (pair? a) (sys:GUARD a 3))
(define (vector-length vec) (sys:LOAD vec 0))
(define (make-vector len init)
  (let ((vec (sys:ALLOC (+ 16 (* len 8)) 7)))
    (sys:STORE vec len 0)
    (do ((i 0 (+ i 1))) ((= i len) vec) (vector-set! vec i init))))
(define (vector-ref vec idx) (sys:LOAD vec (+ 1 idx)))
(define (vector-set! vec idx val) (sys:STORE vec val (+ 1 idx)))
(define (length a)
  (let loop ((len 0) (a a)) (if (pair? a) (loop (+ len 1) (cdr a)) len)))
(define (vector->list vec)
  (let loop ((i (vector-length vec)) (l '()))
    (if (= i 0) l (loop (- i 1) (cons (vector-ref vec (- i 1)) l)))))
(define (list->vector lst)
  (let* ((len (length lst)) (v (make-vector len 0)))
    (do ((i 0 (+ i 1)) (p lst (cdr p))) ((= i len) v) (vector-set! v i (car p)))))

;;; SIMPLEX -- Simplex algorithm.

(define (matrix-rows a) (vector-length a))
(define (matrix-columns a) (vector-length (vector-ref a 0)))
(define (matrix-ref a i j) (vector-ref (vector-ref a i) j))
(define (matrix-set! a i j x) (vector-set! (vector-ref a i) j x))

(define (complain) (display "This shouldn't happen") error)

(define (simplex a m1 m2 m3)
  ;(define *epsilon* 1e-6)
  (define *epsilon* 1e-06)
  (unless (and (>= m1 0) (>= m2 0) (>= m3 0) (= (matrix-rows a) (+ (+ (+ m1 m2) m3) 2)))
    (complain))
  (let* ((m12 (+ (+ m1 m2) 1))
         (m (- (matrix-rows a) 2))
         (n (- (matrix-columns a) 1))
         (l1 (make-vector n 0))
         (l2 (make-vector m 0))
         (l3 (make-vector m2 #f))
         (nl1 n)
         (iposv (make-vector m 0))
         (izrov (make-vector n 0))
         (ip 0)
         (kp 0)
         (bmax 0.0)
         (one? #f)
         (pass2? #t))
    (define (simp1 mm abs?)
      (set! kp (vector-ref l1 0))
      (set! bmax (matrix-ref a mm kp))
      (do ((k 1 (+ k 1)))
           ((>= k nl1))
           (when (positive? (if abs?
                                (- (abs (matrix-ref a mm (vector-ref l1 k))) (abs bmax))
                                (- (matrix-ref a mm (vector-ref l1 k)) bmax)))
             (begin
               (set! kp (vector-ref l1 k))
               (set! bmax (matrix-ref a mm (vector-ref l1 k)))))))
    (define (simp2)
      (set! ip 0)
      (let ((q1 0.0) (flag? #f))
        (do ((i 0 (+ i 1)))
             ((= i m))
             (if flag?
                 (when (< (matrix-ref a (vector-ref l2 i) kp) (- *epsilon*))
                   (let ((q
                            (/ (- (matrix-ref a (vector-ref l2 i) 0))
                               (matrix-ref a (vector-ref l2 i) kp))))
                     (cond
                       ((< q q1) (set! ip (vector-ref l2 i)) (set! q1 q))
                       ((= q q1)
                         (let ((qp 0.0) (q0 0.0))
                           (let loop ((k 1))
                             (if (<= k n)
                                 (begin
                                   (set! qp (/ (- (matrix-ref a ip k)) (matrix-ref a ip kp)))
                                   (set! q0
                                     (/ (- (matrix-ref a (vector-ref l2 i) k))
                                        (matrix-ref a (vector-ref l2 i) kp)))
                                   (if (= q0 qp) (loop (+ k 1))))))
                           (if (< q0 qp) (set! ip (vector-ref l2 i))))))))
                 (when (< (matrix-ref a (vector-ref l2 i) kp) (- *epsilon*))
                   (set! q1
                     (/ (- (matrix-ref a (vector-ref l2 i) 0)) (matrix-ref a (vector-ref l2 i) kp)))
                   (set! ip (vector-ref l2 i))
                   (set! flag? #t))))))
    (define (simp3 one?)
      (let ((piv (/ (matrix-ref a ip kp))))
        (do ((ii 0 (+ ii 1)))
             ((= ii (+ m (if one? 2 1))))
             (unless (= ii ip)
               (matrix-set! a ii kp (* piv (matrix-ref a ii kp)))
               (do ((kk 0 (+ kk 1)))
                    ((= kk (+ n 1)))
                    (unless (= kk kp)
                      (matrix-set! a
                                   ii
                                   kk
                                   (- (matrix-ref a ii kk)
                                      (* (matrix-ref a ip kk) (matrix-ref a ii kp))))))))
        (do ((kk 0 (+ kk 1)))
             ((= kk (+ n 1)))
             (unless (= kk kp) (matrix-set! a ip kk (* (- piv) (matrix-ref a ip kk)))))
        (matrix-set! a ip kp piv)))
    (do ((k 0 (+ k 1)))
         ((= k n))
         (vector-set! l1 k (+ k 1))
         (vector-set! izrov k k))
    (do ((i 0 (+ i 1)))
         ((= i m))
         (when (negative? (matrix-ref a (+ i 1) 0)) (complain))
         (vector-set! l2 i (+ i 1))
         (vector-set! iposv i (+ n i)))
    (do ((i 0 (+ i 1))) ((= i m2)) (vector-set! l3 i #t))
    (when (positive? (+ m2 m3))
      (do ((k 0 (+ k 1)))
           ((= k (+ n 1)))
           (do ((i (+ m1 1) (+ i 1)) (sum 0.0 (+ sum (matrix-ref a i k))))
                ((> i m) (matrix-set! a (+ m 1) k (- sum)))))
      (let loop ()
        (simp1 (+ m 1) #f)
        (cond
          ((<= bmax *epsilon*)
            (cond
              ((< (matrix-ref a (+ m 1) 0) (- *epsilon*)) (set! pass2? #f))
              ((<= (matrix-ref a (+ m 1) 0) *epsilon*)
                (let loop ((ip1 m12))
                  (if (<= ip1 m)
                      (cond
                        ((= (vector-ref iposv (- ip1 1)) (- (+ ip n) 1))
                          (simp1 ip1 #t)
                          (cond
                            ((positive? bmax) (set! ip ip1) (set! one? #t))
                            (else (loop (+ ip1 1)))))
                        (else (loop (+ ip1 1))))
                      (do ((i (+ m1 1) (+ i 1)))
                           ((>= i m12))
                           (when (vector-ref l3 (- i (+ m1 1)))
                             (do ((k 0 (+ k 1)))
                                  ((= k (+ n 1)))
                                  (matrix-set! a i k (- (matrix-ref a i k)))))))))
              (else (simp2) (if (zero? ip) (set! pass2? #f) (set! one? #t)))))
          (else (simp2) (if (zero? ip) (set! pass2? #f) (set! one? #t))))
        (when one?
          (set! one? #f)
          (simp3 #t)
          (cond
            ((>= (vector-ref iposv (- ip 1)) (- (+ n m12) 1))
              (let loop ((k 0))
                (cond
                  ((and (< k nl1) (not (= kp (vector-ref l1 k)))) (loop (+ k 1)))
                  (else
                    (set! nl1 (- nl1 1))
                    (do ((is k (+ is 1)))
                         ((>= is nl1))
                         (vector-set! l1 is (vector-ref l1 (+ is 1))))
                    (matrix-set! a (+ m 1) kp (+ (matrix-ref a (+ m 1) kp) 1.0))
                    (do ((i 0 (+ i 1)))
                         ((= i (+ m 2)))
                         (matrix-set! a i kp (- (matrix-ref a i kp))))))))
            ((and (>= (vector-ref iposv (- ip 1)) (+ n m1))
                  (vector-ref l3 (- (vector-ref iposv (- ip 1)) (+ m1 n))))
              (vector-set! l3 (- (vector-ref iposv (- ip 1)) (+ m1 n)) #f)
              (matrix-set! a (+ m 1) kp (+ (matrix-ref a (+ m 1) kp) 1.0))
              (do ((i 0 (+ i 1)))
                   ((= i (+ m 2)))
                   (matrix-set! a i kp (- (matrix-ref a i kp))))))
          (let ((t (vector-ref izrov (- kp 1))))
            (vector-set! izrov (- kp 1) (vector-ref iposv (- ip 1)))
            (vector-set! iposv (- ip 1) t))
          (loop))))
    (and pass2?
         (let loop ()
           (simp1 0 #f)
           (cond
             ((positive? bmax)
               (simp2)
               (cond
                 ((zero? ip) #t)
                 (else
                   (simp3 #f)
                   (let ((t (vector-ref izrov (- kp 1))))
                     (vector-set! izrov (- kp 1) (vector-ref iposv (- ip 1)))
                     (vector-set! iposv (- ip 1) t))
                   (loop))))
             (else (cons iposv (cons izrov '()))))))))

(define (test input)
  (let* ((r0 (make-vector 5 0))
         (r1 (make-vector 5 0))
         (r2 (make-vector 5 0))
         (r3 (make-vector 5 0))
         (r4 (make-vector 5 0))
         (r5 (make-vector 5 0))
         (a (make-vector 6 0)))
    (vector-set! r0 0 0.0)
    (vector-set! r0 1 1.0)
    (vector-set! r0 2 1.0)
    (vector-set! r0 3 3.0)
    (vector-set! r0 4 -0.5)
    (vector-set! r1 0 740.0)
    (vector-set! r1 1 -1.0)
    (vector-set! r1 2 0.0)
    (vector-set! r1 3 -2.0)
    (vector-set! r1 4 0.0)
    (vector-set! r2 0 0.0)
    (vector-set! r2 1 0.0)
    (vector-set! r2 2 -2.0)
    (vector-set! r2 3 0.0)
    (vector-set! r2 4 7.0)
    (vector-set! r3 0 0.5)
    (vector-set! r3 1 0.0)
    (vector-set! r3 2 -1.0)
    (vector-set! r3 3 1.0)
    (vector-set! r3 4 -2.0)
    (vector-set! r4 0 9.0)
    (vector-set! r4 1 -1.0)
    (vector-set! r4 2 -1.0)
    (vector-set! r4 3 -1.0)
    (vector-set! r4 4 -1.0)
    (vector-set! r5 0 0.0)
    (vector-set! r5 1 0.0)
    (vector-set! r5 2 0.0)
    (vector-set! r5 3 0.0)
    (vector-set! r5 4 0.0)
    (vector-set! a 0 r0)
    (vector-set! a 1 r1)
    (vector-set! a 2 r2)
    (vector-set! a 3 r3)
    (vector-set! a 4 r4)
    (vector-set! a 5 r5)
    (simplex a 2 1 1)))

(define (main n res) (if (= n 0) res (main (- n 1) (test 740.0))))
;'(#(4 1 3 2) #(0 5 7 6))
;1000000 
(display (main 1000000 0))
