fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: master
    hooks:
      - id: clang-format
      - id: clang-tidy
      - id: oclint
        args: ["-rc=SHORT_VARIABLE_NAME=1","-rc=CYCLOMATIC_COMPLEXITY=15"]
#      - id: uncrustify
      - id: cppcheck
      - id: cpplint
        args: ["--filter=-build/include_subdir,-whitespace/comments"]
      - id: include-what-you-use