fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: master
    hooks:
      - id: clang-format
        args: [--style=Google]
      - id: clang-tidy
      - id: oclint
        args: []
      - id: uncrustify
      - id: cppcheck
      - id: cpplint
        args: [--filter=-build/include_subdir]
      - id: include-what-you-use