fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: master
    hooks:
      - id: clang-format
      - id: clang-tidy
        args: ["-checks=clang-diagnostic-*,clang-analyzer-*,bugprone*,modernize*,performance*,readability-*,-modernize-use-trailing-return-type,-modernize-avoid-c-arrays,-readability-magic-numbers,-readability-identifier-length,-clang-analyzer-security*,-performance-no-int-to-ptr,-bugprone-easily-swappable-parameters,-readability-function-cognitive-complexity,-bugprone-sizeof-expression,-clang-analyzer-core.uninitialized.*,-clang-analyzer-core.UndefinedBinaryOperatorResult"]
      - id: oclint
        args: ["-rc=SHORT_VARIABLE_NAME=1","-rc=CYCLOMATIC_COMPLEXITY=15","-rc=NCSS_METHOD=50"]
#      - id: uncrustify
      - id: cppcheck
      - id: cpplint
        args: ["--filter=-build/include_subdir,-whitespace/comments"]
      - id: include-what-you-use