#!/usr/bin/env python3
"""
Generate Scheme opcode definitions from bc.h.

Reads the OPS macro in bc.h and emits lib/opcodes.scm with
per-opcode constants and per-type opcode groupings.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys
from dataclasses import dataclass
from typing import List

@dataclass
class Opcode:
  name: str
  op_type: str

OPS_PATTERN = re.compile(r"^\s*X\((?P<name>[A-Z0-9_]+)\s*,\s*(?P<type>[A-Z0-9_]+)\)\s*\\?\s*$")

def parse_ops(header_path: pathlib.Path) -> List[Opcode]:
  ops: List[Opcode] = []

  for raw_line in header_path.read_text().splitlines():
    match = OPS_PATTERN.match(raw_line)
    if not match:
      continue
    ops.append(Opcode(match.group("name"), match.group("type")))
  if not ops:
    raise RuntimeError(f"No opcode definitions found in {header_path}")
  return ops

def write_scheme(ops: List[Opcode], output_path: pathlib.Path) -> None:
  type_order: list[str] = []
  type_to_index: dict[str, int] = {}
  type_to_ops: dict[str, list[str]] = {}

  for opcode in ops:
    if opcode.op_type not in type_to_index:
      type_to_index[opcode.op_type] = len(type_order)
      type_order.append(opcode.op_type)
    type_to_ops.setdefault(opcode.op_type, []).append(f"{opcode.name}")

  lines: list[str] = []
  lines.append(";; Auto-generated by gen_opcodes.py. Do not edit.\n")

  lines.append("(define opcodes '(\n");
  for idx, opcode in enumerate(ops):
    lines.append(f"({opcode.name} . {idx})\n")

  lines.append("))\n")

  for op_type in type_order:
    type_name = op_type.lower()
    ops_list = " ".join(type_to_ops[op_type])
    lines.append(f"(define ops_{type_name} '({ops_list}))\n")

  output_path.parent.mkdir(parents=True, exist_ok=True)
  new_contents = "".join(lines)
  if output_path.exists():
    old = output_path.read_text()
    if old == new_contents:
      return
  output_path.write_text(new_contents)


def main() -> int:
  parser = argparse.ArgumentParser(description="Generate Scheme opcode definitions.")
  parser.add_argument("--header", default="bc.h", type=pathlib.Path)
  parser.add_argument("--output", default=pathlib.Path("lib/opcodes.scm"), type=pathlib.Path)
  args = parser.parse_args()

  ops = parse_ops(args.header)
  write_scheme(ops, args.output)
  return 0


if __name__ == "__main__":
  sys.exit(main())
