(define failures 0)
(define (same-real? actual expected)
  (if (nan? expected) (nan? actual) (= actual expected)))

(define (check text expected)
  (let ((actual (guard (e (#t 'raised)) (string->number text))))
    (if (not (if (number? expected)
                 (and (number? actual)
                      (same-real? (real-part actual) (real-part expected))
                      (same-real? (imag-part actual) (imag-part expected))
                      (eq? (exact? actual) (exact? expected)))
                 (eq? actual expected)))
        (begin
          (set! failures (+ failures 1))
          (display "FAIL ")
          (write text)
          (display " => ")
          (write actual)
          (newline)))))

(check "1e-2+3i" (make-rectangular 0.01 3))
(check "1+2e-2i" (make-rectangular 1 0.02))
(check "1e-10000" 0.0)
(check "-1e10000" -inf.0)
(check "0e10000" 0.0)
(check "1e10000junk" #f)
(check "#e0.1" 1/10)
(check "#e1e2" 100)
(check "#e1.25e1" 25/2)
(check "#e1e-2+3i" (make-rectangular 1/100 3))
(check "1+2+3i" #f)
(check "1+2-3i" #f)
(check "1@-1" (make-polar 1 -1))
(check "1@+1" (make-polar 1 1))
(check "#i1/0" +inf.0)
(check "#i-1/0" -inf.0)
(check "#i0/0" +nan.0)
(check "#i1+2/0i" (make-rectangular 1.0 +inf.0))
(check "#i1-2/0i" (make-rectangular 1.0 -inf.0))
(check "1/0" #f)
(check "#e1/0" #f)
(check "0/0" #f)
(check "1+2/0i" #f)
(check "#i1/0junk" #f)
(check "4.9406564584124654e-324" (/ 2.22507e-308 (expt 2.0 52)))
(check "#i+i" (make-rectangular 0.0 1.0))
(check "-2/5" -2/5)
(check "1e2i" #f)
(check "1e" #f)
(check "1e-" #f)
(if (> failures 0) (error "string->number" "regressions failed" failures))
(display "string-to-number-ok")
(newline)
