(import (scheme base) (scheme char) (scheme write) (srfi 69))
(define (check a b) (unless (equal? a b) (error "include-ci" a b)))
(include-ci "test/regression/unicode-include.inc")
(check strasse "Straße")
(check |MixedCase| 17)
(check PreservedCase 19)
(let ((h (make-hash-table string-ci=?)))
  (hash-table-set! h "Straße" 42)
  (check (hash-table-ref h "STRASSE") 42))
(display "Unicode include and hash passed\n")
