(define-library (builders)
  (import (scheme base) (scheme case-lambda))
  (include "builders.scm")
  (export make-variable
          variable?
          variable-name
          variable-assigned
          variable-library-name
          build-variable
          ir-application?
          ir-application-fun
          ir-application-args
          ir-application-ann
          ir-application-well-known
          build-application
          set-ir-application-fun!
          set-ir-application-args!
          set-ir-application-well-known!
          ir-conditional?
          ir-conditional-test
          ir-conditional-then
          ir-conditional-else
          ir-conditional-ann
          build-conditional
          set-ir-conditional-test!
          set-ir-conditional-then!
          set-ir-conditional-else!
          ir-reference?
          ir-reference-var
          ir-reference-global?
          ir-reference-mutable?
          ir-reference-ann
          build-lexical-reference
          build-global-reference
          ir-assignment?
          ir-assignment-var
          ir-assignment-exp
          ir-assignment-global?
          ir-assignment-ann
          build-lambda
          set-ir-lambda-cases!
          set-ir-lambda-freevars!
          set-ir-lambda-well-known!
          build-letrec*
          set-ir-letrec*-bindings!
          set-ir-letrec*-body!
          build-loop
          set-ir-loop-args!
          set-ir-loop-body!
          ir-let?
          ir-let-bindings
          ir-let-body
          ir-let-ann
          ir-letrec*?
          ir-letrec*-bindings
          ir-letrec*-body
          ir-letrec*-ann
          ir-loop?
          ir-loop-args
          ir-loop-body
          ir-loop-name
          ir-loop-ann
          build-lexical-assignment
          build-global-assignment
          build-set
          build-let
          build-define
          ir-primcall?
          ir-primcall-name
          ir-primcall-args
          ir-primcall-ann
          build-primcall
          set-ir-primcall-args!
          build-quote
          build-begin
          walk-ir
          ir-void?
	  build-void
          ir-lambda?
          ir-lambda-cases
          ir-lambda-name
          ir-lambda-freevars
          ir-lambda-ann
          ir-lambda-well-known
          ir-quote?
          ir-quote-datum
          ir-begin?
          ir-begin-exps
          ir-begin-ann
          ir-define?
          ir-define-var
          ir-define-exp
          ir-define-ann
          ir->sexp
	  ir-pp))
