(import (scheme base) (scheme write) (r7expand) (scheme cxr) (scheme file) (scheme read)
        (scheme process-context) (library) (builders) (srfi 1) (expander))
(include "pp.scm")
(expander-setup)
(let loop ((opts (cdr (command-line))))
  (cond
    ((null? opts))
    ((equal? (car opts) "-I")
      (library-paths (cons (cadr opts) (library-paths)))
      (loop (cddr opts)))
    ((equal? (car opts) "-l")
      (pretty-print (ir-pp (load-library-from-file (cadr opts))))
      (loop (cddr opts)))
    ((and (null? (cdr opts)))
     (pretty-print (ir->sexp (load-program-from-file (car opts)))))
    (else (error "invalid command line arguments" opts))))
(newline)
