#!/usr/bin/env python3
"""Manually regenerate Unicode tables; never invoked by the build."""
import argparse
import bisect
import hashlib
from pathlib import Path
import urllib.request

VERSION = '17.0.0'
FILES = ['UnicodeData.txt', 'DerivedCoreProperties.txt', 'PropList.txt',
         'CaseFolding.txt', 'SpecialCasing.txt']
LIMIT = 0x110000


def records(path):
    for line in path.read_text().splitlines():
        line = line.split('#')[0].strip()
        if line:
            yield [x.strip() for x in line.split(';')]


def ranges(values):
    result = []
    for n in sorted(values):
        if result and result[-1][1] + 1 == n:
            result[-1][1] = n
        else:
            result.append([n, n])
    return result


def mappings(values):
    result = []
    for n, target in sorted(values.items()):
        delta = target - n
        if delta == 0:
            continue
        if result and result[-1][3] == delta:
            a, b, stride, _ = result[-1]
            step = n - b
            if (a == b and step in (1, 2)) or step == stride:
                result[-1][1:3] = [n, step]
                continue
        result.append([n, n, 1, delta])
    return result


def verify(rows, expected, mapping=False):
    starts = [r[0] for r in rows]
    for n in range(LIMIT):
        i = bisect.bisect_right(starts, n) - 1
        r = rows[i] if i >= 0 else None
        if mapping:
            got = n + r[3] if r and n <= r[1] and (n-r[0]) % r[2] == 0 else n
            assert got == expected.get(n, n), (hex(n), got)
        else:
            assert bool(r and n <= r[1]) == (n in expected), hex(n)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--cache', type=Path, default=Path(__file__).parent / 'cache')
    parser.add_argument('--offline', action='store_true')
    args = parser.parse_args()
    cache = args.cache / VERSION
    cache.mkdir(parents=True, exist_ok=True)
    hashes = []
    for name in FILES:
        path = cache / name
        if not path.exists():
            if args.offline:
                parser.error(f'missing cached file: {path}')
            data = urllib.request.urlopen(f'https://www.unicode.org/Public/{VERSION}/ucd/{name}').read()
            path.write_bytes(data)
        hashes.append(f';; {name}: {hashlib.sha256(path.read_bytes()).hexdigest()}')
    props = {k: set() for k in ['Alphabetic', 'Uppercase', 'Lowercase', 'White_Space']}
    for name in FILES[1:3]:
        for r in records(cache / name):
            if r[1] in props:
                bounds = [int(x, 16) for x in r[0].split('..')]
                props[r[1]].update(range(bounds[0], bounds[-1]+1))
    simple = {k: {} for k in ['upper', 'lower', 'fold']}
    full = {k: {} for k in simple}
    digits = {}
    initial, subsequent = set(), set()
    allowed = set('Lu Ll Lt Lm Lo Mn Mc Me Nd Nl No Pd Pc Po Sc Sm Sk So Co'.split())
    first = None
    for r in records(cache / FILES[0]):
        n = int(r[0], 16)
        if r[1].endswith(', First>'):
            first = n
            continue
        start = first if r[1].endswith(', Last>') else n
        first = None
        if r[2] in allowed:
            subsequent.update(range(max(128, start), n+1))
            if r[2] not in ('Nd', 'Mc', 'Me'):
                initial.update(range(max(128, start), n+1))
        if r[6]:
            digits[n] = int(r[6])
        for kind, field in [('upper', 12), ('lower', 13)]:
            if r[field]:
                simple[kind][n] = int(r[field], 16)
    initial.update((0x200c, 0x200d))
    subsequent.update((0x200c, 0x200d))
    for r in records(cache / 'CaseFolding.txt'):
        n, status = int(r[0], 16), r[1]
        seq = tuple(int(x, 16) for x in r[2].split())
        if status in ('C', 'S'):
            assert len(seq) == 1
            simple['fold'][n] = seq[0]
        if status in ('C', 'F'):
            full['fold'][n] = seq
    for r in records(cache / 'SpecialCasing.txt'):
        if not r[4]:
            for kind, field in [('lower', 1), ('upper', 3)]:
                full[kind][int(r[0], 16)] = tuple(int(x, 16) for x in r[field].split())
    output = [f';; Generated by generate.py; Unicode {VERSION}. Do not edit.', *hashes]
    def vector(name, rows):
        output.append(f'(define unicode-{name}\n  \'#(')
        for row in rows:
            output.append('    ' + ' '.join(str(x) for x in row))
        output.append('  ))')
    for name, values in {**props, 'initial': initial, 'subsequent': subsequent}.items():
        rows = ranges(values)
        verify(rows, values)
        vector(name.lower().replace('_', '-'), rows)
    zeros = [n for n, value in digits.items() if value == 0]
    assert {n+i: i for n in zeros for i in range(10)} == digits
    vector('zeros', [zeros])
    for kind in simple:
        rows = mappings(simple[kind])
        verify(rows, simple[kind], True)
        vector(kind, rows)
        exceptions = {n: seq for n, seq in full[kind].items()
                      if seq != (simple[kind].get(n, n),)}
        vector(kind+'-full', [[n, '"'+''.join(f'\\x{x:x};' for x in seq)+'"']
                             for n, seq in sorted(exceptions.items())])
        for n in range(LIMIT):
            assert exceptions.get(n, (simple[kind].get(n, n),)) == full[kind].get(n, (simple[kind].get(n, n),))
    target = Path(__file__).parent / 'tables.scm'
    temp = target.with_suffix('.tmp')
    temp.write_text('\n'.join(output)+'\n')
    temp.replace(target)
    print(f'Validated all scalar lookups; wrote {target} ({target.stat().st_size} bytes)')


if __name__ == '__main__':
    main()
