(import (scheme base)
        (scheme char)
        (scheme file)
        (scheme read)
        (scheme write)
        (scheme process-context)
        (srfi 1)
        (srfi 69))

;; Generate Scheme opcode definitions from bc.h.
;;
;; Usage:
;;   gen-opcodes.scm --header bc.h --output opcodes.scm

(define (char-ascii-whitespace? ch)
  (or (char=? ch #\space)
      (char=? ch #\tab)
      (char=? ch #\newline)
      (char=? ch #\return)))

(define (string-trim-both s)
  (let ((len (string-length s)))
    (let left ((start 0))
      (if (and (< start len) (char-ascii-whitespace? (string-ref s start)))
          (left (+ start 1))
          (let right ((end len))
            (if (and (< start end)
                     (char-ascii-whitespace? (string-ref s (- end 1))))
                (right (- end 1))
                (substring s start end)))))))

(define (string-join strings sep)
  (if (null? strings)
      ""
      (let loop ((parts (cdr strings))
                 (out (car strings)))
        (if (null? parts)
            out
            (loop (cdr parts) (string-append out sep (car parts)))))))

(define (split-on-chars s delims)
  (let loop ((chars (string->list s))
             (field '())
             (fields '()))
    (cond
     ((null? chars)
      (reverse (cons (list->string (reverse field)) fields)))
     ((memv (car chars) delims)
      (loop (cdr chars)
            '()
            (cons (list->string (reverse field)) fields)))
     (else
      (loop (cdr chars)
            (cons (car chars) field)
            fields)))))

(define (nonempty-string? s)
  (not (= (string-length s) 0)))

(define (tokenize-op-line line)
  (filter nonempty-string?
          (map string-trim-both
               (split-on-chars line '(#\( #\) #\, #\\)))))

;; Parse lines of the form:
;;
;;   X(NAME, TYPE)
;;   X(NAME, TYPE) \
;;
;; Returns either (cons name type) or #f.
(define (parse-op-line raw-line)
  (let* ((line (string-trim-both raw-line))
         (tokens (tokenize-op-line line)))
    (and (= (length tokens) 3)
         (string=? (first tokens) "X")
         (let ((name (second tokens))
               (op-type (third tokens)))
           (cons name op-type)))))

(define (parse-ops header-path)
  (call-with-input-file header-path
    (lambda (port)
      (let loop ((ops '()))
        (let ((line (read-line port)))
          (if (eof-object? line)
              (if (null? ops)
                  (error "No opcode definitions found" header-path)
                  (reverse ops))
              (let ((op (parse-op-line line)))
                (loop (if op (cons op ops) ops)))))))))

(define (ascii-string-downcase s)
  (string-map char-downcase s))

(define (group-ops-by-type ops)
  (let ((type-to-ops (make-hash-table string=? string-hash)))
    (for-each
     (lambda (op)
       (let ((name (car op))
             (op-type (cdr op)))
         (hash-table-update!/default
          type-to-ops
          op-type
          (lambda (names)
            (cons name names))
          '())))
     ops)
    type-to-ops))

(define (write-output ops)
  (let ((type-to-ops (group-ops-by-type ops)))
    (display ";; Auto-generated by gen-opcodes.scm. Do not edit.\n")
    (display "(define opcodes '(\n")
    (for-each
     (lambda (op idx)
       (display "(")
       (display (car op))
       (display " . ")
       (display (number->string idx))
       (display ")\n"))
     ops
     (iota (length ops)))
    (display "))\n")
    (hash-table-walk
     type-to-ops
     (lambda (op-type names)
       (display "\n")
       (display "(define ops_")
       (display (ascii-string-downcase op-type))
       (display " '(")
       (display (string-join names " "))
       (display "))\n")))))

(define (parse-args args)
  (let loop ((args args)
             (header "bc.h")
             (output "lib/opcodes.scm"))
    (cond
     ((null? args)
      (cons header output))
     ((and (string=? (car args) "--header")
           (pair? (cdr args)))
      (loop (cddr args) (cadr args) output))
     ((and (string=? (car args) "--output")
           (pair? (cdr args)))
      (loop (cddr args) header (cadr args)))
     (else
      (error "usage: gen-opcodes.scm [--header bc.h] [--output lib/opcodes.scm]")))))

(define (main)
  (let* ((parsed (parse-args (cdr (command-line)))))
    (with-output-to-file (cdr parsed)
      (lambda ()
        (write-output (parse-ops (car parsed)))))))

(main)
