(import (scheme case-lambda) (scheme base) (scheme write) (prefix (hawk sys) sys:) (srfi 69))

(define (check-shared? shared x port)
  (let ((seen (hash-table-ref/default (cdr shared) x #f)))
    (cond
      ((integer? seen) (display "#" port) (display seen port) (display "#" port) #t)
      (seen
        (display "#" port)
        (display (car shared) port)
        (hash-table-set! (cdr shared) x (car shared))
        (set-car! shared (+ (car shared) 1))
        (display "=" port)
        #f)
      (else #f))))

(define (extract-shared-objects x cyclic-only?)
  (let ((seen (make-hash-table eq?)))
    ;; find shared references
    (let find ((x x))
      ;; only interested in pairs, vectors and records
      (when (or (pair? x) (vector? x))
        ;; increment the count
        (hash-table-update!/default seen x (lambda (n) (+ n 1)) 0)
        ;; walk if this is the first time
        (cond
          ((> (hash-table-ref seen x) 1))
          ((pair? x) (find (car x)) (find (cdr x)))
          ((vector? x)
            (do ((i 0 (+ i 1))) ((= i (vector-length x))) (find (vector-ref x i)))))
        ;; delete if this shouldn't count as a shared reference
        (if (and cyclic-only? (<= (hash-table-ref/default seen x 0) 1))
            (hash-table-delete! seen x))))
    ;; extract shared references
    (let ((res (make-hash-table eq?)))
      (hash-table-walk seen (lambda (k v) (if (> v 1) (hash-table-set! res k #t))))
      res)))

(define (write-pair-body arg port shared write-one)
  (display "(" port)
  (write-one (car arg) port)
  (let write-cdr ((arg (cdr arg)))
    (cond
      ((and (pair? arg) (not (hash-table-ref/default (cdr shared) arg #f)))
        (display " " port)
        (write-one (car arg) port)
        (write-cdr (cdr arg)))
      ((null? arg) (display ")" port))
      (else (display " . " port) (write-one arg port) (display ")" port)))))

(define (write-all arg port type)
  (define (write-symbol sym port)
    (let ((s (symbol->string sym)))
      ;; We need to detect symbols that need to be wrapped in ||
      ;; A pile of stuff just copied from chibi's implementation.
      (let* ((bars
                (or (= 0 (string-length s))
                   (equal? "." s)
                   (char-numeric? (string-ref s 0))
                   (and (> (string-length s) 1)
                        (and (or (eq? #\+ (string-ref s 0)) (eq? #\- (string-ref s 0)))
                             (or (char-numeric? (string-ref s 1))
                                (eq? #\. (string-ref s 1))
                                (eq? #\i (string-ref s 1))
                                (and (> (string-length s) 3)
                                     (eq? #\n (char-downcase (string-ref s 1)))
                                     (eq? #\a (char-downcase (string-ref s 2)))
                                     (eq? #\n (char-downcase (string-ref s 3)))))))))
             (valid
                (let loop ((i 0))
                  (cond
                    ((= i (string-length s)) #t)
                    ((<= (char->integer (string-ref s i)) (char->integer #\space)) #f)
                    ((memq (string-ref s i)
                           '(#\( #\) #\" #\| #\newline #\return #\space #\tab #\; #\\ #\# #\,))
                      #f)
                    (else (loop (+ i 1)))))))
        (if (and (not bars) valid)
            (display s port)
            (begin
              (display "|" port)
              (do ((i 0 (+ i 1)))
                   ((= i (string-length s)))
                   (let ((c (string-ref s i)))
                     (case c
                       ((#\\ #\|) (display "\\" port) (display c port))
                       (else (display c port)))))
              (display "|" port))))))
  (let ((shared (cons 0 (extract-shared-objects arg (not (eq? type 'shared))))))
    (let write ((arg arg) (port port))
      (cond
        ((null? arg) (display "()" port))
        ((pair? arg)
          (unless (check-shared? shared arg port)
            (write-pair-body arg port shared write)))
        ((vector? arg)
          (unless (check-shared? shared arg port)
            (display "#" port)
            (write (vector->list arg) port)))
        ((char? arg)
          (case arg
            ((#\newline) (display "#\\newline" port))
            ((#\tab) (display "#\\tab" port))
            ((#\space) (display "#\\space" port))
            ((#\return) (display "#\\return" port))
            ((#\alarm) (display "#\\alarm" port))
            ((#\backspace) (display "#\\backspace" port))
            ((#\delete) (display "#\\delete" port))
            ((#\escape) (display "#\\escape" port))
            ((#\null) (display "#\\null" port))
            (else (display "#\\" port) (display arg port))))
        ((string? arg)
          (display "\"" port)
          (for-each (lambda (chr)
                      (case chr
                        ((#\") (display "\\\"" port))
                        ((#\\) (display "\\\\" port))
                        ((#\newline) (display "\\n" port))
                        ((#\tab) (display "\\t" port))
                        ((#\return) (display "\\r" port))
                        ((#\alarm) (display "\\a" port))
                        ((#\backspace) (display "\\b" port))
                        ((#\delete) (display "\\x7F;" port))
                        ((#\escape) (display "\\x1B;" port))
                        ((#\null) (display "\\x00;" port))
                        (else (display chr port))))
                    (string->list arg))
          (display "\"" port))
        ((symbol? arg) (write-symbol arg port))
        (else (display arg port))))))

(define display
  (case-lambda
    ((x) (display x (current-output-port)))
    ((x port)
      (let ((shared
              (and (or (pair? x) (vector? x)) (cons 0 (extract-shared-objects x #t)))))
        (let display ((x x) (port port))
          (cond
            ((flonum? x)
              (display (sys:FOREIGN_CALL '(string "flonum_string" (double)) x) port))
            ((number? x) (display (number->string x) port))
            ((char? x) (write-char x port))
            ((vector? x)
              (unless (and shared (check-shared? shared x port))
                (display "#" port)
                (display (vector->list x) port)))
            ((pair? x)
              (unless (and shared (check-shared? shared x port))
                (write-pair-body x port shared display)))
            ((symbol? x) (display (symbol->string x) port))
            ((procedure? x)
              (display "#<procedure " port)
              (display (sys:LOAD (sys:LOAD x 1) 1) port)
              (display ">" port))
            ((eq? x #t) (display "#t" port))
            ((eq? x #f) (display "#f" port))
            ((eq? x '()) (display "()" port))
            ((eof-object? x) (display "#<eof>" port))
            ((undefined? x) (display "#<undefined>" port))
            ((port? x) (display "#<port>" port))
            ((record? x)
              (display "#<record" port)
              (let ((typ (record-ref x 0)))
                (when (record? typ) (display " " port) (display (record-type-name typ) port)))
              (display ">" port))
            ((string? x)
              (do ((i 0 (+ i 1)))
                   ((= i (string-length x)))
                   (write-char (string-ref x i) port)))
            ((bytevector? x)
              (display "#u8(" port)
              (do ((i 0 (+ i 1)))
                   ((= i (bytevector-length x)))
                   (unless (= i 0) (display " " port))
                   (display (bytevector-u8-ref x i) port))
              (display ")" port))
            (else (error "Bad type in display: " x)))))
      x)))

(define write
  (case-lambda
    ((arg) (write arg (current-output-port)))
    ((arg port) (write-all arg port 'write))))

(define write-simple
  (case-lambda
    ((arg) (write-simple arg (current-output-port)))
    ((arg port) (write-all arg port 'simple))))

(define write-shared
  (case-lambda
    ((arg) (write-shared arg (current-output-port)))
    ((arg port) (write-all arg port 'shared))))

;;;;;;;;;;; Reader

(define read-buf (make-string 1000))
(define (maybe-lower-case port s)
  (if (port-fold-case port)
      (let ((s (string-copy s)))
        (do ((i 0 (+ i 1)))
             ((= i (string-length s)) s)
             (string-set! s i (char-downcase (string-ref s i)))))
      s))
(define (read-error msg . irritants)
  (raise (make-error-object 'read msg irritants)))

(define (list->u8 lst)
  (let* ((len (length lst)) (bv (make-bytevector len)))
    (do ((i 0 (+ i 1)) (lst lst (cdr lst)))
         ((= i len) bv)
         (bytevector-u8-set! bv i (car lst)))))

(define read
  (case-lambda
    (() (read (current-input-port)))
    ((port)
      (define line 1)
      (define holes #f)
      (define (read2 port)
        (define (read-to-delimited)
          (let loop ((res 0) (c (peek-char port)))
            (if (eof-object? c)
                (if (not (= 0 res)) (substring read-buf 0 res) c)
                (case c
                  ((#\( #\) #\" #\| #\newline #\return #\space #\tab #\;)
                    (substring read-buf 0 res))
                  (else
                    (string-set! read-buf res (read-char port))
                    (loop (+ res 1) (peek-char port)))))))
        (define (skip-whitespace)
          (let loop ()
            (let ((c (peek-char port)))
              (cond
                ((eof-object? c) c)
                ((char=? #\newline c) (set! line (+ 1 line)) (read-char port) (loop))
                ((char-whitespace? c) (read-char port) (loop))))))
        (define (skip-horizontal-whitespace)
          (let loop ()
            (let ((c (peek-char port)))
              (cond
                ((eof-object? c) c)
                ((char=? #\newline c))
                ((char-whitespace? c) (read-char port) (loop))))))
        (define (skip-whitespace-and-comments)
          (let loop ()
            (let ((c (peek-char port)))
              (cond
                ((eof-object? c) c)
                ((char=? #\newline c) (set! line (+ 1 line)) (read-char port) (loop))
                ((char-whitespace? c) (read-char port) (loop))
                ((char=? #\; c) (skip-line) (loop))))))
        (define (skip-whitespace-and-sexp-comments)
          (let loop ()
            (let ((c (peek-char port)))
              (cond
                ((eof-object? c) c)
                ((char=? #\# c)
                  (read-char port)
                  (if (not (char=? #\; (read-char port))) (read-error "Invalid hash"))
                  (read-one)
                  (loop))
                ((char=? #\newline c) (set! line (+ 1 line)) (read-char port) (loop))
                ((char-whitespace? c) (read-char port) (loop))
                ((char=? #\; c) (skip-line) (loop))))))
        (define (skip-line)
          (let loop ()
            (let ((c (read-char port)))
              (if (eof-object? c) c (if (char=? c #\newline) (set! line (+ 1 line)) (loop))))))
        (define (read-label)
          (let loop ((res 0) (seen #f))
            (let ((c (peek-char port)))
              (cond
                ((eof-object? c) (read-error "Invalid label"))
                ((char-numeric? c)
                  (read-char port)
                  (loop (+ (* res 10) (- (char->integer c) (char->integer #\0))) #t))
                ((or (char=? c #\=) (char=? c #\#))
                  (if seen res (read-error "Invalid label")))
                (else (read-error "Invalid label"))))))
        (define (read-escape)
          (let ((c (read-char port)))
            (if (eof-object? c) (read-error "Incomplete escape sequence"))
            (case c
              ((#\a) #\alarm)
              ((#\n) #\newline)
              ((#\r) #\return)
              ((#\t) #\tab)
              ((#\b) #\backspace)
              ((#\tab #\space) (skip-line) (skip-horizontal-whitespace) #f)
              ((#\newline) (skip-horizontal-whitespace) #f)
              ((#\x #\X)
                (let* ((delim (read-to-delimited))
                       (ch (string->number delim 16))
                       (next (read-char port)))
                  (if (not (eq? #\; next))
                      (read-error "Invalid hex string escape")
                      (integer->char ch))))
              (else c))))
        (define (read-delimited term)
          (let loop ((res '()) (c (read-char port)))
            (cond
              ((eof-object? c)
                (read-error "incomplete object:" (list->string (reverse res)) "line: " line))
              ((char=? #\\ c)
                (let ((es (read-escape)))
                  (if es
                      (loop (cons es res) (read-char port))
                      (loop res (read-char port)))))
              ((char=? term c) (list->string (reverse res)))
              (else (loop (cons c res) (read-char port))))))
        (define (lower-case string)
          (do ((i 0 (+ i 1)))
               ((= i (string-length string)) string)
               (string-set! string i (char-downcase (string-ref string i)))))
        (define (special-initial? c)
          (memv c '(#\! #\$ #\% #\& #\* #\/ #\: #\< #\= #\> #\? #\@ #\^ #\_ #\~)))
        (define (initial? c) (or (char-alphabetic? c) (special-initial? c)))
        (define (digit? c) (char-numeric? c))
        (define (explicit-sign? c) (memv c '(#\+ #\-)))
        (define (special-subsequent? c)
          (or (explicit-sign? c) (eqv? c #\.) (eqv? c #\@)))
        (define (subsequent? c) (or (initial? c) (digit? c) (special-subsequent? c)))
        (define (sign-subsequent? c)
          (or (initial? c) (explicit-sign? c) (eqv? c #\@)))
        (define (dot-subsequent? c) (or (sign-subsequent? c) (eqv? c #\.)))
        (define (identifier? s)
          (define (all-subsequent? start)
            (let loop ((i start))
              (if (>= i (string-length s))
                  #t
                  (and (subsequent? (string-ref s i)) (loop (+ i 1))))))
          (let ((n (string-length s)))
            (if (zero? n)
                #f
                (let ((c0 (string-ref s 0)))
                  (cond
                    ((initial? c0) (all-subsequent? 1))
                    ((explicit-sign? c0)
                      (cond
                        ((= n 1) #t)
                        ((and (= n 2) (eqv? (string-ref s 1) #\.)) #t)
                        ((sign-subsequent? (string-ref s 1)) (all-subsequent? 2))
                        ((and (>= n 3)
                              (eqv? (string-ref s 1) #\.)
                              (dot-subsequent? (string-ref s 2)))
                          (all-subsequent? 3))
                        (else #f)))
                    ((eqv? c0 #\.)
                      (if (> n 1) (and (dot-subsequent? (string-ref s 1)) (all-subsequent? 2)) #f))
                    (else #f))))))
        (define (read-list)
          (define line-start line)
          (let loop ((res '()))
            (skip-whitespace-and-comments)
            (let ((c (peek-char port)))
              (cond
                ((eof-object? c)
                  (read-error "EOF found while parsing list starting on line "
                              line-start
                              " and ending "
                              line))
                ((char=? c #\)) (read-char port) (reverse res))
                ((char=? c #\.)
                  (let ((token (read-to-delimited)))
                    (if (= 1 (string-length token))
                        (let ((fin (read-one)))
                          (skip-whitespace-and-sexp-comments)
                          (if (not (eq? #\) (read-char port)))
                              (read-error "Invalid dotted list")
                              (append (reverse res) fin)))
                        (loop (cons (cond
                                      ((string->number token) => (lambda (num) num))
                                      ((identifier? token) (string->symbol (lower-case token)))
                                      (else (read-error "Invalid symbol" token)))
                                    res)))))
                (else (loop (cons (read-one) res)))))))
        (define (patch x)
          (define (fill-hole x) (if (procedure? x) (fill-hole (x)) x))
          (cond
            ((pair? x)
              (patch (car x))
              (patch (cdr x))
              (when (procedure? (car x)) (set-car! x (fill-hole (car x))))
              (when (procedure? (cdr x)) (set-cdr! x (fill-hole (cdr x)))))
            ((vector? x)
              (do ((i 0 (+ i 1)))
                   ((= i (vector-length x)))
                   (patch (vector-ref x i))
                   (when (procedure? (vector-ref x i))
                     (vector-set! x i (fill-hole (vector-ref x i))))))))
        (define named-chars
          '(("tab" . #\tab)
            ("space" . #\space)
            ("return" . #\return)
            ("newline" . #\newline)
            ("alarm" . #\alarm)
            ("backspace" . #\backspace)
            ("delete" . #\delete)
            ("escape" . #\escape)
            ("null" . #\null)))
        (define delims '(#\( #\) #\; #\| #\" #\space))
        (define (do-read-char)
          (let ((ch (peek-char port)))
            (if (memv ch delims)
                (read-char port)
                (let ((token (read-to-delimited)))
                  (cond
                    ((= 1 (string-length token)) (string-ref token 0))
                    ((assoc token named-chars string=?) => cdr)
                    (else (read-error "Error invalid char: " token)))))))
        (define (skip-comment)
          (let loop ((depth 0))
            (case (read-char port)
              ((#\#) (loop (if (char=? #\| (peek-char port)) (+ 1 depth) depth)))
              ((#\|)
                (if (char=? #\# (peek-char port))
                    (if (= 0 depth) (read-char port) (loop (- depth 1)))
                    (loop depth)))
              ((#\newline) (set! line (+ 1 line)) (loop depth))
              (else
                (if (eof-object? (peek-char port))
                    (read-error "unterminated comment")
                    (loop depth))))))
        (define (read-hash)
          (let ((c (peek-char port)))
            (case c
              ((#\0 #\1 #\2 #\3 #\4 #\5 #\6 #\7 #\8 #\9)
                (let* ((label (read-label)) (next (read-char port)))
                  (case next
                    ((#\#)
                      (if (not (and holes (hash-table-exists? holes label)))
                          (read-error "Label referenced before defined:" label)
                          (hash-table-ref holes label)))
                    ((#\=)
                      (when (and holes (hash-table-exists? holes label))
                        (read-error "Multiple labels:" label))
                      (let* ((cell (cons #f #f)) (thunk (lambda () (car cell))))
                        (unless holes (set! holes (make-hash-table eq?)))
                        (hash-table-set! holes label thunk)
                        (let ((res (read-one)))
                          (when (procedure? res) (read-error "self label reference:" label))
                          (set-car! cell res)
                          res)))
                    (else (read-error "Invalid label")))))
              ((#\!)
                (read-char port)
                (let ((bang (read-to-delimited)))
                  (port-fold-case-set! port
                                       (cond
                                         ((string=? bang "no-fold-case") #f)
                                         ((string=? bang "fold-case") #t)
                                         (else (read-error "Invalid #!:" bang))))
                  (read-one)))
              ((#\|) (skip-comment) (read-one))
              ((#\;) (read-char port) (read-one) (read-one))
              ((#\() (read-char port) (list->vector (read-list)))
              ((#\\) (read-char port) (do-read-char))
              ((#\t #\T #\f #\F)
                (let ((v (lower-case (read-to-delimited))))
                  (cond
                    ((string=? "f" v) #f)
                    ((string=? "t" v) #t)
                    ((string=? "true" v) #t)
                    ((string=? "false" v) #f)
                    (else (read-error "Can't parse hash token:" v)))))
              ((#\b #\B #\o #\O #\d #\D #\x #\X #\i #\I #\e #\E)
                (string->number (string-append "#" (read-to-delimited))))
              ((#\u)
                (read-char port)
                (if (not (char=? #\8 (peek-char port)))
                    (read-error "Not a bytevector:" (peek-char port))
                    (read-char port))
                (let ((ls (read-one)))
                  (if (not (list? ls)) (read-error "Not a bytevector list:" ls) (list->u8 ls))))
              (else (read-error "Unknown hash: " c)))))
        (define (read-one)
          (skip-whitespace)
          (let ((c (peek-char port)))
            (case (peek-char port)
              ((#\#) (read-char port) (read-hash))
              ((#\() (read-char port) (read-list))
              ((#\)) (read-char port) (read-error "Extra list terminator found"))
              ((#\") (read-char port) (read-delimited #\"))
              ((#\;) (read-char port) (skip-line) (read-one))
              ((#\|) (read-char port) (string->symbol (read-delimited #\|)))
              ((#\') (read-char port) (list 'quote (read-one)))
              ((#\`) (read-char port) (list 'quasiquote (read-one)))
              ((#\,)
                (read-char port)
                (case (peek-char port)
                  ((#\@) (read-char port) (list 'unquote-splicing (read-one)))
                  (else (list 'unquote (read-one)))))
              (else
                (let ((token (read-to-delimited)))
                  (cond
                    ((eof-object? token) token)
                    ((string->number token) => (lambda (num) num))
                    ((identifier? token) (string->symbol (maybe-lower-case port token)))
                    (else (read-error "Invalid symbol" token))))))))
        (let ((res (read-one)))
          (unless (or (not holes) (= 0 (hash-table-size holes))) (patch res))
          res))
      (read2 port))))
