(import (scheme base) (scheme case-lambda) (scheme write))
(define read
  (case-lambda
    (() (read (current-input-port)))
    ((port)
      (define line 1)
      (define (read2 port)
        (define (read-to-delimited)
          (let loop ((res 0) (c (peek-char port)))
            (if (eof-object? c)
                (if (not (= 0 res)) (substring read-buf 0 res) c)
                (case c
                  ((#\( #\) #\" #\| #\newline #\return #\space #\tab #\;)
                    (substring read-buf 0 res))
                  (else
                    (string-set! read-buf res (read-char port))
                    (loop (+ res 1) (peek-char port)))))))
        (define (skip-whitespace)
          (let loop ()
            (let ((c (peek-char port)))
              (cond
                ((eof-object? c) c)
                ((char=? #\newline c) (set! line (+ 1 line)) (read-char port) (loop))
                ((char-whitespace? c) (read-char port) (loop))))))
        (define (skip-whitespace-and-comments)
          (let loop ()
            (let ((c (peek-char port)))
              (cond
                ((eof-object? c) c)
                ((char=? #\newline c) (set! line (+ 1 line)) (read-char port) (loop))
                ((char-whitespace? c) (read-char port) (loop))
                ((char=? #\; c) (skip-line) (loop))))))
        (define (skip-line)
          (let loop ()
            (let ((c (read-char port)))
              (if (eof-object? c) c (if (char=? c #\newline) (set! line (+ 1 line)) (loop))))))
        (define (read-escape)
          (let ((c (read-char port)))
            (if (eof-object? c) (error "Incomplete escape sequence"))
            (case c
              ((#\a) #\alarm)
              ((#\n) #\newline)
              ((#\r) #\return)
              ((#\t) #\tab)
              ((#\b) #\backspace)
              ((#\tab #\space) (skip-line) (skip-whitespace) #f)
              ((#\newline) (skip-whitespace) #f)
              ((#\x #\X)
                (let* ((delim (read-to-delimited))
                       (ch (string->number delim 16))
                       (next (read-char port)))
                  (if (not (eq? #\; next))
                      (error "Invalid hex string escape")
                      (integer->char ch))))
              (else c))))
        (define (read-delimited term)
          (let loop ((res 0) (c (read-char port)))
            (cond
              ((eof-object? c)
                (error "incomplete object:" (substring read-buf 0 res) "line: " line))
              ((char=? #\\ c)
                (let ((es (read-escape)))
                  (if es
                      (begin (string-set! read-buf res es) (loop (+ 1 res) (read-char port)))
                      (loop res (read-char port)))))
              ((char=? term c) (substring read-buf 0 res))
              (else (string-set! read-buf res c) (loop (+ 1 res) (read-char port))))))
        (define (lower-case string)
          (do ((i 0 (+ i 1)))
               ((= i (string-length string)) string)
               (string-set! string i (char-downcase (string-ref string i)))))
        (define (read-list)
          (define line-start line)
          (let loop ((res '()))
            (skip-whitespace-and-comments)
            (let ((c (peek-char port)))
              (cond
                ((eof-object? c)
                  (error "EOF found while parsing list starting on line "
                         line-start
                         " and ending "
                         line))
                ((char=? c #\)) (read-char port) (reverse res))
                ((char=? c #\.)
                  (let ((token (read-to-delimited)))
                    (if (= 1 (string-length token))
                        (let ((fin (read-one)))
                          (skip-whitespace-and-comments)
                          (if (not (eq? #\) (read-char port)))
                              (error "Invalid dotted list")
                              (append (reverse res) fin)))
                        (loop (cons (cond
                                      ((string->number token) => (lambda (num) num))
                                      (else (string->symbol (lower-case token))))
                                    res)))))
                (else (loop (cons (read-one) res)))))))
        (define named-chars
          '(("tab" . #\tab)
            ("space" . #\space)
            ("return" . #\return)
            ("newline" . #\newline)
            ("alarm" . #\alarm)
            ("backspace" . #\backspace)
            ("delete" . #\delete)
            ;("escape" . #\escape)
            ;		      ("null" . #\null)
          ))
        (define delims '(#\( #\) #\; #\| #\" #\space))
        (define (do-read-char)
          (let ((ch (peek-char port)))
            (if (memv ch delims)
                (read-char port)
                (let ((token (read-to-delimited)))
                  (cond
                    ((= 1 (string-length token)) (string-ref token 0))
                    ((assoc token named-chars string=?) => cdr)
                    (else (error "Error invalid char: " token)))))))
        (define (skip-comment)
          (let loop ((depth 0))
            (case (read-char port)
              ((#\#) (loop (if (char=? #\| (peek-char port)) (+ 1 depth) depth)))
              ((#\|)
                (if (char=? #\# (peek-char port))
                    (if (= 0 depth) (read-char port) (loop (- depth 1)))
                    (loop depth)))
              ((#\newline) (set! line (+ 1 line)) (loop depth))
              (else
                (if (eof-object? (peek-char port))
                    (error "unterminated comment")
                    (loop depth))))))
        (define (read-hash)
          (let ((c (peek-char port)))
            (case c
              ((#\|) (skip-comment))
              ((#\;) (read-char port) (read-one) (read-one))
              ((#\() (read-char port) (list->vector (read-list)))
              ((#\\) (read-char port) (do-read-char))
              ((#\t #\T #\f #\F)
                (let ((v (lower-case (read-to-delimited))))
                  (cond
                    ((string=? "f" v) #f)
                    ((string=? "t" v) #t)
                    ((string=? "true" v) #t)
                    ((string=? "false" v) #f)
                    (else (error "Can't parse hash token:" v)))))
              ((#\b #\B #\o #\O #\d #\D #\x #\X #\i #\I #\e #\E)
                (string->number (string-append "#" (read-to-delimited))))
              ((#\u)
                (read-char port)
                (if (not (char=? #\8 (peek-char port)))
                    (error "Not a bytevector:" (peek-char port))
                    (read-char port))
                (let ((ls (read-one)))
                  (if (not (list? ls)) (error "Not a bytevector list:" ls) ls)))
              (else (error "Unknown hash: " c)))))
        (define (read-one)
          (skip-whitespace)
          (let ((c (peek-char port)))
            (case (peek-char port)
              ((#\#) (read-char port) (read-hash))
              ((#\() (read-char port) (read-list))
              ((#\)) (read-char port) (error "Extra list terminator found"))
              ((#\") (read-char port) (read-delimited #\"))
              ((#\;) (read-char port) (skip-line) (read-one))
              ((#\|) (read-char port) (string->symbol (read-delimited #\|)))
              ((#\') (read-char port) (list 'quote (read-one)))
              ((#\`) (read-char port) (list 'quasiquote (read-one)))
              ((#\,)
                (read-char port)
                (case (peek-char port)
                  ((#\@) (read-char port) (list 'unquote-splicing (read-one)))
                  (else (list 'unquote (read-one)))))
              (else
                (let ((token (read-to-delimited)))
                  (cond
                    ((eof-object? token) token)
                    ((string->number token) => (lambda (num) num))
                    (else (string->symbol token))))))))
        (read-one))
      (read2 port))))
