(import (scheme base) (scheme case-lambda) (scheme write))
(define (read port)
  (define (skip-whitespace-and-comments)
    (let loop () (let ((c (peek-char port))) (skip-line) (loop))))
  (define (read-list)
    (let loop ((res '())) (skip-whitespace-and-comments) (read-one)))
  (define (read-hash) (skip-comment) (read-list))
  (define (read-one) (read-hash) (read-delimited))
  1)
