(import (scheme base) (scheme write) (scheme inexact) (scheme complex))

(define pass-count 0)
(define fail-count 0)

(define-syntax check
  (syntax-rules ()
    ((_ expr expected)
     (let ((result expr))
       (if (equal? result expected)
           (set! pass-count (+ pass-count 1))
           (begin
             (set! fail-count (+ fail-count 1))
             (display "FAIL: ")
             (write 'expr)
             (display " expected ")
             (write expected)
             (display " got ")
             (write result)
             (newline)))))))

(define (raises? thunk)
  (guard (exn (#t #t))
    (thunk)
    #f))

;; Numeric type predicates
(check (exact? 42) #t)
(check (exact? 3/4) #t)
(check (exact? 3+4i) #t)
(check (exact? 3.0) #f)
(check (inexact? 3.0) #t)
(check (inexact? 3+4.0i) #t)
(check (inexact? 3+4i) #f)
(check (rational? 3/4) #t)
(check (rational? 3.0) #t)
(check (rational? 3+4i) #f)
(check (real? 3/4) #t)
(check (real? 3+4i) #f)
(check (complex? 3+4i) #t)
(check (number? 'a) #f)

;; Sign and parity predicates
(check (zero? 0) #t)
(check (zero? 0.0) #t)
(check (zero? 1/10) #f)
(check (positive? 3/4) #t)
(check (positive? -3/4) #f)
(check (negative? -3/4) #t)
(check (negative? 3/4) #f)
(check (even? -4) #t)
(check (odd? -3) #t)
(check (even? 4.0) #t)
(check (odd? 3.0) #t)
(check (raises? (lambda () (even? 3.5))) #t)
(check (raises? (lambda () (odd? 3+4i))) #t)

;; Exact and inexact conversion
(check (= (exact 0.5) 1/2) #t)
(check (= (inexact 1/2) 0.5) #t)
(check (exact? (exact 3.0)) #t)
(check (inexact? (inexact 3/4)) #t)

;; Rounding preserves exactness for exact inputs.
(check (truncate 17/3) 5)
(check (truncate -17/3) -5)
(check (floor 17/3) 5)
(check (floor -17/3) -6)
(check (ceiling 17/3) 6)
(check (ceiling -17/3) -5)
(check (round 5/2) 2)
(check (round 7/2) 4)
(check (round -5/2) -2)
(check (= (truncate 2.75) 2.0) #t)
(check (= (floor -2.75) -3.0) #t)
(check (= (ceiling -2.75) -2.0) #t)
(check (= (round 2.5) 2.0) #t)
(check (= (round 3.5) 4.0) #t)

;; Quotient, remainder, and modulo signs.
(check (quotient 17 5) 3)
(check (quotient -17 5) -3)
(check (quotient 17 -5) -3)
(check (remainder 17 5) 2)
(check (remainder -17 5) -2)
(check (remainder 17 -5) 2)
(check (modulo 17 5) 2)
(check (modulo -17 5) 3)
(check (modulo 17 -5) -3)
(check (raises? (lambda () (quotient 1 0))) #t)
(check (raises? (lambda () (remainder 1 0))) #t)
(check (raises? (lambda () (modulo 1 0))) #t)

;; Complex construction and projections.
(check (real-part (make-rectangular 3 4)) 3)
(check (imag-part (make-rectangular 3 4)) 4)
(check (real-part (make-rectangular 3.0 4)) 3.0)
(check (imag-part 7) 0)
(check (= (magnitude 3+4i) 5) #t)
(check (= (magnitude -3-4i) 5) #t)
(check (= (angle 1) 0.0) #t)
(check (< (abs (- (angle -1) 3.141592653589793)) 1e-12) #t)

(newline)
(display "Number functions: ")
(write pass-count)
(display " passed, ")
(write fail-count)
(display " failed")
(newline)
