#!/bin/bash

set -euo pipefail

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
repo_root="$script_dir/.."

sudo --preserve-env=GC_SPACE --preserve-env=GC_COLLECT \
  perf record --no-inherit --call-graph=dwarf -e cycles -g -k1 "$repo_root/build/hawk" --dump "$@"
